name: everest_crypto
description: Flutter challenge Everest.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  

        

  cupertino_icons: ^1.0.2
  decimal: ^2.3.0
  intl: ^0.17.0
  flutter_riverpod: ^2.0.0-dev.9
  fl_chart: ^0.55.1
  dio: ^4.0.6
  json_annotation: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.4.0
  build_runner: ^2.2.1
  faker: ^2.0.0
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0
 


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/mont/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/mont/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/mont/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/mont/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/mont/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/mont/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/mont/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/mont/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/mont/Montserrat-Black.ttf
          weight: 900
        

    - family: Source_Sans_Pro
      fonts:
        - asset: assets/fonts/source_sans_pro/SourceSansPro-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/source_sans_pro/SourceSansPro-Light.ttf
          weight: 300
        - asset: assets/fonts/source_sans_pro/SourceSansPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/source_sans_pro/SourceSansPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/source_sans_pro/SourceSansPro-Bold.ttf
          weight: 700
        
